server:
  port: 9099

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
       defaultZone: http://127.0.0.1:8761/eureka/
#       defaultZone: http://localhost:8094/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5

spring:
  application:
    name: school-service
  main:
    allow-circular-references: true

logging:
  level:
    com.example.demo: DEBUG