server:
  port: 8060
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Patients   
    username: root
    password: Sarvesh143
  jpa:
    properties:
      dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update  
      
  application:
    name: PATIENT-MS
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8062/eureka/  
      
management:
  endpoints:
    web:
      exposure:
        include: circuitbreakerevents 
        
#  endpoint:
#    health:
#      show-details: always 
      
resilience4j:
  circuitbreaker:
    configs:
      default:
        failure-rate-threshold: 50
        wait-duration-in-open-state: 1000ms
        event-consumer-buffer-size: 10
    instances:
      patientsCircuitBreaker:
        base-config: default
        register-health-indicator: true
        sliding-window-size: 10
        sliding-window-type: COUNT_BASED
        minimum-number-of-calls: 10
        permitted-number-of-calls-in-half-open-state: 5
        automatic-transition-from-open-to-half-open-enabled: true
        #record-successful-outcomes: true
        ignore-exceptions: java.lang.IllegalStateException
        failure-rate-threshold: 40
        slow-call-duration-threshold: 500ms
        slow-call-rate-threshold: 50
        wait-duration-in-open-state: 5000ms
                